export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SET_SUCCESS = "SET_SUCCESS";

export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const GET_USER_DATA_START = "GET_USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_EDIT_PROFILE_START = "GET_EDIT_PROFILE_START";
export const GET_EDIT_PROFILE_SUCCESS = "GET_EDIT_PROFILE_SUCCESS";
export const GET_EDIT_PROFILE_FAIL = "GET_EDIT_PROFILE_FAIL";

export const GET_MY_PROJECTS_START = "GET_MY_PROJECTS_START";
export const GET_MY_PROJECTS_SUCCESS = "GET_MY_PROJECTS_SUCCESS";
export const GET_MY_PROJECTS_FAIL = "GET_MY_PROJECTS_FAIL";

export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_SUCCESS = "GET_MY_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const GET_ALL_CHECKLIST_START = "GET_ALL_CHECKLIST_START";
export const GET_ALL_CHECKLIST_SUCCESS = "GET_ALL_CHECKLIST_SUCCESS";
export const GET_ALL_CHECKLIST_FAIL = "GET_ALL_CHECKLIST_FAIL";

export const CREATE_CHECKLIST_START = "CREATE_CHECKLIST_START";
export const CREATE_CHECKLIST_SUCCESS = "CREATE_CHECKLIST_SUCCESS";
export const CREATE_CHECKLIST_FAIL = "CREATE_CHECKLIST_FAIL";

export const UPDATE_CHECKLIST_START = "UPDATE_CHECKLIST_START";
export const UPDATE_CHECKLIST_SUCCESS = "UPDATE_CHECKLIST_SUCCESS";
export const UPDATE_CHECKLIST_FAIL = "UPDATE_CHECKLIST_FAIL";

